### PR TITLE
change the add-on installation source to use AMO

### PR DESCRIPTION
**Pull request by lonnen**
switched the installation link from people.mozilla to addons.mozilla

This should resolve issue #110

### CODE REVIEW

**Comment by bwinton** [comment]
Is that _actually_ the issue, because my understanding of the only-AMO-addons change was that it wouldn't affect Nightly or Aurora (and Nightly is 38, which is what it was reported on, and what I tested it on)…

**Comment by lonnen** [comment]
I'm not positive it's the issue, but I think it's better to point people at the AMO install if that's going to be official. I don't know much about the url shortener... I'd have to dig to find out if that's truly immutable.

**Comment by bwinton** [comment]
Works for me.  Lemme know if you have any time to do that digging…  :)

**Comment by lonnen** [comment]
Mail sent. I'll follow up with you in the next few days. Thanks!

**Pull request merged**
