### PR TITLE
Issue 91: Replace Hello icon with Lionel Ritchie, and change default ringtone.

### PR DESCRIPTION
**Pull request by mikeconley**
I can't actually seem to get Hello to "ring", so I have no idea if the .ogg I've supplied will play properly. Perhaps loop.ringtone is part of a codepath that doesn't get hit anymore.

If there's anyone with Hello experience who could tell me how to test this - I'm all ears.

### CODE REVIEW

**Comment by mikeconley** [comment]
I should also point out that I have zero info on the fair use of that audio clip.

**Comment by bwinton** [comment]
@standard8: Do you have any ideas how to get Hello to "ring"?

**Comment by Standard8** [comment]
Ringing only occurs for incoming direct calls (i.e. make a call to a contact). The other ones are all room join notification sounds iirc.

**Comment by bwinton** [comment]
Hey Mike, this doesn't seem to apply anymore.  Did you want to try fixing it up, or see if we can pull @dmose in to fix and test it, or should we just close it?

**Comment by bwinton** [comment]
This has been bitrotting for a while, and I don't even think Hello is a thing anymore, so I think I'm gonna close this PR.  Thanks for the work, though!

**Pull request closed without merging**
