### PR TITLE
Fix the 'Hover to Show' newtab option; Remove icon jittering on mouse…

### PR DESCRIPTION
**Pull request by ahal**
… move

### CODE REVIEW

**Comment by ahal** [comment]
This should fix issue 112 and issue 76. I'm not really sure what that mouse move listener was supposed to be doing.. but the weird jiggling is gone and nothing else seems to break if I remove it. I guess it could be left in if it's serving some sort of purpose.

**Comment by bwinton** [comment]
A lot of images are the wrong aspect ratio, so it would be nice to have some way to scroll them.  That's what the mouse move listener did, so if you're going to remove it, you should add in some way of seeing all the image for ones that are wrongly-sized…  :wink:

**Comment by ahal** [comment]
Oh, I see. Personally I think I'd rather just not be able to see the full image, the moving makes it look sort of buggy (at least on Linux, it's very choppy).

But I don't care that much.. I'll add the mouse move listener back.

**Comment by bwinton** [comment]
If you can think of a better way, I'm all ears!  (I tried using the accellerometer, but apparently newer MacBooks don't have one anymore.  :cry:)  Or, if you wanted to disable it on Linux, I'ld be up for that, too.  :smile:

**Comment by ahal** [comment]
Actually, it should only be added if the newtab icons are set to "Always On", otherwise, as soon as you move the mouse out of the cell, the gif will be hidden again and there's no point in adjusting the position. This is probably why it looks jittery to me, as the oldPreviews are the things that are moving.

**Comment by bwinton** [comment]
Oh, yeah!  I would totally accept that change!

**Comment by ahal** [comment]
Hmm, I don't know how to pull request apparently.. Let me close this and try again.

**Pull request closed without merging**
